// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').controller("crdsMenuCtrl", function($scope, $rootScope, Menu, SecurityContext) {
    $scope.menu = Menu;
    $scope.logout = function() {
      return SecurityContext.logout();
    };
    $scope.loginShow = false;
    $scope.toggleDesktopLogin = function() {
      if (this.loginShow === true) {
        return this.loginShow = false;
      } else {
        return this.loginShow = true;
      }
    };
    $scope.toggleMenuDisplay = function() {
      return this.menu.toggleMobileDisplay();
    };
    return $rootScope.$on('login:hide', function() {
      return $scope.loginShow = false;
    });
  });

}).call(this);
