// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').controller("LoginCtrl", function($scope, SecurityContext, growl) {
    $scope.user = {};
    return $scope.login = function() {
      var promise;
      promise = SecurityContext.login($scope.user.username, $scope.user.password);
      if (this.user.username && this.user.password) {
        $scope.processing = "Logging in...";
        return promise.then(function() {
          return $scope.loginError = void 0;
        }, function(error) {
          console.log(error);
          $scope.processing = null;
          return $scope.loginError = ["Oops!", "Login failed."];
        });
      } else {
        return $scope.loginError = ["Hold up!", "Username/password can't be blank"];
      }
    };
  });

}).call(this);
