// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').controller("MainCtrl", function(Menu) {
    this.menus = Menu.menuData;
    this.toggleMenu = function() {
      return Menu.toggleMobileDisplay();
    };
  });

}).call(this);
