// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("crdsProfile").controller("crdsDatePickerCtrl", function($scope) {
    console.log("date picker controller");
    $scope.today = function() {
      $scope.dt = new Date();
    };
    $scope.clear = function() {
      $scope.dt = null;
    };
    $scope.open = function($event) {
      $event.preventDefault();
      $event.stopPropagation();
      $scope.opened = true;
    };
    $scope.dateOptions = {
      formatYear: "yy",
      startingDay: 1,
      showWeeks: false
    };
    return $scope.today();
  });

}).call(this);
