// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("crdsProfile").controller("crdsProfilePersonal", function($scope, SecurityContext, Profile) {
    Profile.getMaritalStatusValues().then(function(data) {
      return $scope.maritalStatuses = data;
    });
    Profile.getGenderValues().then(function(data) {
      return $scope.genders = data;
    });
    return $scope.savePersonal = function(data) {
      return Profile.saveContact(data);
    };
  });

}).call(this);
