module.exports =
  js: [
      "vendor/js/jquery.js",
      "vendor/js/underscore.js",
      "vendor/js/mediaelement-and-player.min.js",
      "vendor/bower/angular/angular.js",
      "vendor/bower/angular-mocks/angular-mocks.js",
      "vendor/bower/angular-strap/dist/angular-strap.js",
      "vendor/bower/angular-strap/dist/angular-strap.tpl.js",
      "vendor/bower/angular-cookies/angular-cookies.js",
      "vendor/bower/masonry/dist/masonry.pkgd.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/affix.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/alert.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/button.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/carousel.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/collapse.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/dropdown.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/tab.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/transition.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/scrollspy.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/modal.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/tooltip.js",
      "vendor/bower/bootstrap-sass-official/vendor/assets/javascripts/bootstrap/popover.js"]
