devEnv = process.env.NODE_ENV == 'development'

gulp = require 'gulp'
$ = require('gulp-load-plugins')()

require('./tasks/clean')(gulp, $)
require('./tasks/jekyll')(gulp, devEnv, $)
require('./tasks/jekyll_build')(gulp)
require('./tasks/coffee')(gulp, devEnv, $)
require('./tasks/sass')(gulp, devEnv, $)
require('./tasks/server')(gulp, $)
require('./tasks/karma')(gulp)
require('./tasks/watch')(gulp)
require('./tasks/spec_watch')(gulp)
require('./tasks/test')(gulp)
require('./tasks/webdriver')(gulp)
require('./tasks/protractor')(gulp, $)
require('./tasks/ci')(gulp)
require('./tasks/dev')(gulp)
require('./tasks/imagemin')(gulp, $)
require('./tasks/copy')(gulp)
require('./tasks/html')(gulp, $)
require('./tasks/build')(gulp)
require('./tasks/default')(gulp)
require('./tasks/pagespeed')(gulp)
