// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').directive("authForm", function() {
    return {
      restrict: "EA",
      templateUrl: "/templates/login.html",
      controller: "LoginCtrl",
      priority: 0
    };
  });

}).call(this);
