// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').directive('crdsLoadingText', function($timeout, $log) {
    return {
      restrict: 'A',
      scope: {
        'crdsLoadingText': '@',
        'crdsLoading': '='
      },
      link: function($scope, $element, $attrs) {
        var baseDisabled, baseText;
        baseText = $element.html();
        baseDisabled = $attrs.disabled;
        $scope.$watch('crdsLoading', function(value) {
          var text;
          if (value) {
            $attrs.$set('disabled', true);
            text = $scope.$parent.$eval($scope.crdsLoadingText);
            if (!text) {
              text = $scope.crdsLoadingText;
            }
            return $element.html(text);
          } else {
            $element.html(baseText);
            return $attrs.$set('disabled', baseDisabled);
          }
        });
        return $scope.$parent.$watch($attrs.ngDisabled, function(value) {
          $log.log("Button disabled: " + value);
          return baseDisabled = value;
        });
      }
    };
  });

}).call(this);
