// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').directive("crdsMenu", function() {
    return {
      controller: "crdsMenuCtrl",
      templateUrl: "/templates/crdsMenu.html",
      require: "?authForm",
      priority: 99,
      scope: {
        menus: "=crdsMenu",
        securityContext: "="
      }
    };
  });

}).call(this);
