// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').directive("hideOnMobileMenu", function(Menu) {
    return {
      link: function(scope, element, attrs) {
        scope.menu = Menu;
        return scope.$watch("menu.isMobileShowing", function(isShowing) {
          if (scope.menu.isMobileShowing) {
            return element.addClass("show");
          } else {
            return element.removeClass("show");
          }
        });
      }
    };
  });

}).call(this);
