// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').directive('randomBlock', function() {
    return {
      restrict: 'C',
      compile: function(telement, tattrs) {
        var children, visible;
        children = _.map(telement.children(), function(child) {
          return angular.element(child);
        });
        _.each(children, function(child) {
          return child.addClass('hidden');
        });
        visible = _.sample(children);
        return visible.removeClass('hidden');
      }
    };
  });

}).call(this);
