// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('crossroads').factory("Menu", function($window) {
    var Menu;
    Menu = (function() {
      function Menu(menuData) {
        this.menuData = menuData;
      }

      Menu.prototype.toggleMobileDisplay = function() {
        return this.isMobileShowing = !this.isMobileShowing;
      };

      Menu.prototype.collapsed = function(index) {
        return index !== this.selectedMenuItem;
      };

      Menu.prototype.toggleMenuItem = function(index) {
        if (this.collapsed(index)) {
          return this.selectedMenuItem = index;
        } else {
          return this.selectedMenuItem = null;
        }
      };

      return Menu;

    })();
    return new Menu($window.menuData);
  });

}).call(this);
