var util = require('util');

module.exports = function(app) {
  app.route('/getMaritalStatus')
    .get(function(req, res) {
      mockPayload = '[[7,"Dating"],[3,"Divorced"],[2,"Married"],[5,"Partnered"],[6,"Separated"],[1,"Single"],[4,"Widowed"]]';
      res.send(mockPayload);
    });

  app.route('/getGenders')
    .get(function(req, res) {
      mockPayload = '[[2,"Female"],[1,"Male"]]';
      res.send(mockPayload);
    })

  app.route('/getContact/:recordId')
    .get(function(req, res) {

      var data = '"Data":[[2,false,null,"Doe, Johnathon","Mr.",null,"Johnathon","Andrew","Doe",null,null,"John","/Date(1306900800000-0400)/","Male",1,"Married",2,"Active",1,"Your Church",2,"Company",6,null,null,null,null,"john@crds.com",false,null,null,null,null,"***Default, Contact",1462553,null,null,null,null,null,null,null,null,"24598d92-b7e0-4b45-85f9-e378070b5b67",null,null,null,null,null,null,null,"***Default, Contact",2,0,null,null]]';

      var fields = '"Fields":[{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":0,"Name":"Contact_ID","Description":null,"DisplayName":"Contact ID","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":true,"IsReadOnly":true,"IsRequired":true,"IsRestricted":false,"Size":-1,"SortOrder":1},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":9,"Index":1,"Name":"Company","Description":null,"DisplayName":"Company","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":true,"IsRestricted":false,"Size":-1,"SortOrder":2},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":2,"Name":"Company_Name","Description":null,"DisplayName":"Company Name","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":50,"SortOrder":3},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":3,"Name":"Display_Name","Description":"For Indiviauls: Last_Name, First_Name","DisplayName":"Display Name","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":true,"IsRestricted":false,"Size":75,"SortOrder":4},' +
        '{"DataType":0,"Index":4,"Name":"Prefix_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":5,"Name":"Prefix_ID","Description":null,"DisplayName":"Prefix","ForeignPageId":364,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":5},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":6,"Name":"First_Name","Description":null,"DisplayName":"First Name","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":50,"SortOrder":6},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":7,"Name":"Middle_Name","Description":null,"DisplayName":"Middle Name","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":50,"SortOrder":7},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":8,"Name":"Last_Name","Description":null,"DisplayName":"Last Name","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":50,"SortOrder":8},' +
        '{"DataType":0,"Index":9,"Name":"Suffix_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":10,"Name":"Suffix_ID","Description":null,"DisplayName":"Suffix","ForeignPageId":395,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":9},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":11,"Name":"Nickname","Description":null,"DisplayName":"Nickname","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":50,"SortOrder":10},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":10,"Index":12,"Name":"Date_of_Birth","Description":null,"DisplayName":"Date of Birth","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":11},' +
        '{"DataType":0,"Index":13,"Name":"Gender_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":14,"Name":"Gender_ID","Description":null,"DisplayName":"Gender","ForeignPageId":311,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":12},' +
        '{"DataType":0,"Index":15,"Name":"Marital_Status_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":16,"Name":"Marital_Status_ID","Description":null,"DisplayName":"Marital Status","ForeignPageId":339,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":13},' +
        '{"DataType":0,"Index":17,"Name":"Contact_Status_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":18,"Name":"Contact_Status_ID","Description":"Indicates the over-all relationship between this contact and the organization.","DisplayName":"Contact Status","ForeignPageId":291,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":true,"IsRestricted":false,"Size":-1,"SortOrder":14},' +
        '{"DataType":0,"Index":19,"Name":"Household_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":20,"Name":"Household_ID","Description":null,"DisplayName":"Household","ForeignPageId":327,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":15},' +
        '{"DataType":0,"Index":21,"Name":"Household_Position_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":22,"Name":"Household_Position_ID","Description":null,"DisplayName":"Household Position","ForeignPageId":324,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":16},' +
        '{"DataType":0,"Index":23,"Name":"Participant_Record_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":24,"Name":"Participant_Record","Description":null,"DisplayName":"Participant Record","ForeignPageId":355,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":17},' +
        '{"DataType":0,"Index":25,"Name":"Donor_Record_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":26,"Name":"Donor_Record","Description":null,"DisplayName":"Donor Record","ForeignPageId":299,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":18},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":27,"Name":"Email_Address","Description":"email addresses are NOT case sensitive.  They can only contain letters, numbers, dashes, underscores, and the @ sign.","DisplayName":"Email Address","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":254,"SortOrder":19},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":9,"Index":28,"Name":"Bulk_Email_Opt_Out","Description":null,"DisplayName":"Bulk Email Opt Out","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":true,"IsRestricted":false,"Size":-1,"SortOrder":20},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":29,"Name":"Mobile_Phone","Description":"Format: 999-123-1234","DisplayName":"Mobile Phone","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":25,"SortOrder":21},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":30,"Name":"Company_Phone","Description":"Format: 999-123-1234 x123","DisplayName":"Company Phone","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":25,"SortOrder":22},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":31,"Name":"Pager_Phone","Description":null,"DisplayName":"Pager Phone","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":25,"SortOrder":23},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":32,"Name":"Fax_Phone","Description":null,"DisplayName":"Fax Phone","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":25,"SortOrder":24},' +
        '{"DataType":0,"Index":33,"Name":"User_Account_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":34,"Name":"User_Account","Description":null,"DisplayName":"User Account","ForeignPageId":401,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":25},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":35,"Name":"Web_Page","Description":null,"DisplayName":"Web Page","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":254,"SortOrder":26},' +
        '{"DataType":0,"Index":36,"Name":"Industry_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":37,"Name":"Industry_ID","Description":null,"DisplayName":"Industry","ForeignPageId":328,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":27},' +
        '{"DataType":0,"Index":38,"Name":"Occupation_ID_Text"},{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":5,"Index":39,"Name":"Occupation_ID","Description":null,"DisplayName":"Occupation","ForeignPageId":347,"IsForeignKey":true,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":28},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":40,"Name":"SSN/EIN","Description":null,"DisplayName":"SSN/EIN","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":15,"SortOrder":29},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":12,"Index":41,"Name":"Anniversary_Date","Description":null,"DisplayName":"Anniversary Date","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":30},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":4,"Index":42,"Name":"HS_Graduation_Year","Description":null,"DisplayName":"HS Graduation Year","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":31},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":17,"Index":43,"Name":"Contact_GUID","Description":null,"DisplayName":"Contact GUID","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":true,"IsRestricted":false,"Size":-1,"SortOrder":36},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":44,"Name":"Facebook_Account","Description":null,"DisplayName":"Facebook Account","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":50,"SortOrder":37},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":45,"Name":"Twitter_Account","Description":null,"DisplayName":"Twitter Account","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":50,"SortOrder":38},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":46,"Name":"ID_Card","Description":null,"DisplayName":"ID Card","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":50,"SortOrder":39},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":9,"Index":47,"Name":"Email_Unlisted","Description":null,"DisplayName":"Email Unlisted","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":42},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":9,"Index":48,"Name":"Mobile_Phone_Unlisted","Description":null,"DisplayName":"Mobile Phone Unlisted","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":43},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":9,"Index":49,"Name":"Remove_From_Directory","Description":null,"DisplayName":"Remove From Directory","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":-1,"SortOrder":44},' +
        '{"__type":"ExtendedFieldInfo:http://www.thinkministry.com/dataplatform/2012/10/","DataType":0,"Index":50,"Name":"Current_School","Description":null,"DisplayName":"Current School","ForeignPageId":null,"IsForeignKey":false,"IsPrimaryKey":false,"IsReadOnly":false,"IsRequired":false,"IsRestricted":false,"Size":75,"SortOrder":45},' +
        '{"DataType":0,"Index":51,"Name":"dp_RecordName"},' +
        '{"DataType":5,"Index":52,"Name":"dp_FileID"},' +
        '{"DataType":5,"Index":53,"Name":"dp_RecordStatus"},' +
        '{"DataType":5,"Index":54,"Name":"dp_TaskId"},' +
        '{"DataType":5,"Index":55,"Name":"dp_TaskAction"}]';

      var selectedRecords = '"SelectedRecords":0';
      var totalRecords = '"TotalRecords":1';

      var mockPayload = '{' + data + ',' + fields + ',' + selectedRecords + ',' + totalRecords + '}';
      res.send(mockPayload);
    })

};
