// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("crossroads", ['templates', 'ngCookies', 'ngStorage', 'crdsAuth', 'crdsSecurityContext', 'angular-growl', 'ui.bootstrap', 'crds-ajax-form', 'crdsProfile', 'fitVids', 'plangular', 'duScroll', 'ui.scrollfix']).config(function(growlProvider, $locationProvider, SecurityContextProvider) {
    $locationProvider.html5Mode(true);
    growlProvider.globalPosition('top-center');
    growlProvider.globalTimeToLive(6000);
    growlProvider.globalDisableIcons(true);
    return SecurityContextProvider.setSessionMinutes(30);
  }).run(function() {}).controller("AppCtrl", function($rootScope, $log, growl) {
    var lookup;
    $rootScope.$on('notify.success', function(event, message) {
      return growl.success(lookup(message));
    });
    $rootScope.$on('notify.info', function(event, message) {
      return growl.info(lookup(message));
    });
    $rootScope.$on('notify.warning', function(event, message) {
      return growl.warning(lookup(message));
    });
    $rootScope.$on('notify.error', function(event, message) {
      return growl.error(lookup(message));
    });
    lookup = function(messageKey) {
      switch (messageKey) {
        case "form.success":
          return "Your request has been submitted successfully";
        case "form.validation.error":
          return "Your request has errors";
        case "form.server.error":
          return "An error has occurred";
        default:
          return messageKey;
      }
    };
  });

}).call(this);
